version: "2.2"

services:

  database:
    image: mysql:latest
    build: .
    restart: "always"
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: controle_de_estoque

  application:
    restart: "always"
    image: lucasnascdevv0042/smtimage:nodeapp
    build: .
    depends_on:
      - database
    ports:
      - 3333:3333
    environment:
      - DB=controle_de_estoque
      - DATABASE_HOST=localhost
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=
