version: "3"

services:

  stm_database:
    container_name: stm_container
    image: mysql:latest
    restart: always
    volumes:
      - /home/lucasfortunato328/smt_volume:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: controle_de_estoque

  application:
    restart: "always"
    image: lucasnascdevv0042/myimage:nodeapp
    links:
      - stm_database
    ports:
      - 3333:3333
